version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    
hooks:
  BeforeInstall:
    - name: Install Dependencies
      timeout: 300
      runas: root
      command: |
        cd /var/www/html
        composer install --no-dev --optimize-autoloader
        npm install
        npm run production
        
  ApplicationStart:
    - name: Start Server
      timeout: 300
      runas: root
      command: |
        cd /var/www/html
        php artisan serve --host=0.0.0.0 --port=8000 &

  ApplicationStop:
    - name: Stop Server
      timeout: 300
      runas: root
      command: |
        pkill -f 'php artisan serve'
