version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - composer install --no-dev
      - npm install
      - npm run production
  pre_build:
    commands:
      - echo Pre-build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - zip -r ../my-laravel-app.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ../my-laravel-app.zip

