version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.0
    commands:
      - composer install --no-dev --optimize-autoloader
      - php artisan migrate --force
  build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
