version: 0.2
phases:
  install:
    commands:
      - echo "Installing Composer dependencies..."
      - composer install --no-dev --optimize-autoloader
      - echo "Running migrations..."
      - php artisan migrate --force
  build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
